name: OpenArc_build5
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - pip
  - pip:
    - transformers==4.52.3
    - optimum[openvino]
    - openvino==2025.2.0
    - openvino-genai==2025.2.0.0
    - fastapi
    - gradio
    - pydantic
    - uvicorn
    - rich-click
    - pyyaml