name: OpenArc_test2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - transformers==4.51.0 --no-deps
    - optimum[openvino]
    - openvino==2025.1.0
    - openvino-tokenizers==2025.1.0.0
    - openvino-genai==2025.1.0.0
    - fastapi
    - gradio
    - pydantic
    - uvicorn