            - name: Zensical Action
  # You may pin to the exact commit or the version.
  # uses: cssnr/zensical-action@4a85be625b4c38e82cb7b3c1c8a9683c86807468
  uses: cssnr/zensical-action@v1.0.7
  with:
    # Zensical Version
    version: # optional
    # Python Version
    python-version: # optional
    # UV Version
    uv-version: # optional
    # Build Directory
    directory: # optional, default is .
    # Build Arguments
    args: # optional, default is -c
    # Site Path
    path: # optional, default is site
    # Checkout Project
    checkout: # optional, default is true
    # Upload: github-pages, artifact, false
    upload: # optional, default is github-pages
    # Artifact Name
    name: # optional, default is artifact
    # Deploy to GitHub Pages
    deploy: # optional, default is true
    # Prepare Script (Before Build)
    prepare: # optional
    # Post Script (After Build)
    post: # optional
    # Add Job Summary
    summary: # optional, default is true
          
